### ISSUE TITLE
Not able to Build the project

### ISSUE THREAD

**Issue by DeepaliBajajDU** [blueperf/acmeair-monolithic-java#11]
Hi
I am doing research on micro service architecture. I am exploring this benchmark application  to get call-graph. But it needs the complied java code in jar format. The provided code is not getting complied. Can anyone please provide me Build file for this application?

**Comment by jdmcclur** [comment]
Hmm, why jar format? This is a java application, so it compiles to a war file which runs on top of an application server. The build instructions are in the readme. Can you tell me what you are doing exactly?

**Comment by jdmcclur** [comment]
No response, so closing.
