### ISSUE TITLE
Running monolithic acme air in a docker container giver error

### ISSUE THREAD

**Issue by rakeshkrishnakumar** [blueperf/acmeair-monolithic-java#9]
have been trying to run monolithic version of acmeair following the link provided in the https://github.com/blueperf/acmeair-monolithic-java.
Could successfully build app and db container and start the application.
Also could load the database. But as soon as the application is invoked by browser to do a login it gives following error
"Unable to load rest/api/login status:403".
For the application docker build have used the file Dockerfile_KS

**Comment by jdmcclur** [comment]
Did you load the database?

**Comment by jdmcclur** [comment]
No response, so closing.
